### ISSUE TITLE
theme readthedocs the same

### ISSUE THREAD

**Issue by yochannah** [yochannah/intermine-homepage-2017#2]
part implemented here: https://github.com/yochannah/im-docs/tree/restyle 

Still to do: 
- make dynamic header with dropdown menu
- check various different page types
- footer needs more work

**Comment by NirmalKumarJoshi** [comment]
Can I work on this issue @yochannah ?

**Comment by yochannah** [comment]
@NirmalKumarJoshi Sure.

**Comment by yochannah** [comment]
closing this issue and moving to https://github.com/intermine/intermine-homepage-2017
