### ISSUE TITLE
Improve accessibility for the contributors page

### ISSUE THREAD

**Issue by JackieBinya** [yochannah/intermine-homepage-2017#5]
Currently, when you perform an accessibility audit using Lighthouse extension (in the Chrome browser) on the [contributors' page](http://intermine.org/contributors/) you get 70%.

The goal is to improve the accessibility score and get it high as possible. Ideally, the goal is a perfect score of 100%.

**Comment by yochannah** [comment]
fixed by #6 🙌 ✨ 🚀
